"""
Build the master per-cell deployment table (task B3).

Three evidence layers exist in separate files and have never been shown together:

  1. accuracy      software, 3 datasets, two evaluation regimes
  2. bench         MSP430 with the sensor detached: latency, power, memory
  3. sensor-in-loop  MSP430 with the MPU6050 actually in the loop

The point of merging them is that they answer different questions and are easy to
conflate. A cell can win on accuracy and lose on latency; power can be identical
across cells while energy per window is not. Every row is therefore labelled with
how the number came about: measured on the device, derived from two measurements,
or computed analytically from the model.

  python build_master_table.py            # write MASTER_TABLE.md
  python build_master_table.py --print    # to stdout only
"""
from __future__ import annotations

import argparse
import glob
import json
from pathlib import Path

import numpy as np

EXP = Path("experiments")
OUT = Path("MASTER_TABLE.md")
CELLS = ["GRU", "LSTM", "FastGRNN"]
KEY = {"GRU": "gru", "LSTM": "lstm", "FastGRNN": "fastgrnn"}

# Datasets whose numbers are reported but carry no ranking claim. Encoded here
# rather than left to be remembered, so nothing downstream quietly counts them
# as a win.
RANK_EXCLUDED = {
    "pamap2": "under the tri-axial restriction no cell reaches useful accuracy there "
              "(most per-class F1 below 0.25, one class never learned) and repeated "
              "identical runs move individual class scores by 0.2-0.5",
}


def jload(name):
    with open(EXP / name, encoding="utf-8") as f:
        return json.load(f)


def tier1_hapt(cell):
    """Equal-capacity accuracy, H=16, 5 seeds, HAPT."""
    files = sorted(glob.glob(str(EXP / f"baseline_{KEY[cell]}_h16_s*_e120.json")))
    v = np.array([json.load(open(f, encoding="utf-8"))["test_macro_f1"] for f in files])
    return v.mean(), v.std()


def budget_hapt(cell):
    """Equal-byte accuracy on HAPT; baselines at their better compression route."""
    d = jload("best_route_summary.json")["hapt"][KEY[cell]]
    if cell == "FastGRNN":
        return d["mean"], d["std"], "low-rank + IHT + Q15"
    route = d["best_route"]
    return d["best_mean"], d[f"{route}_std"], f"{route}-H"


def fmt(v, nd=3):
    return "--" if v is None else f"{v:.{nd}f}"


def build() -> str:
    hw = jload("hardware_bench.json")
    sensor = jload("sensor_in_loop_matrix.json")
    live = {(r["cell"], r["lut"], r["i2c_khz"]): r for r in sensor["runs"]}

    L = []
    add = L.append
    add("# Master deployment table")
    add("")
    add("Generated by `build_master_table.py` — do not edit by hand.")
    add("")
    add(f"Target: {hw['_platform']['mcu']} at {hw['_platform']['clock_mhz']} MHz, "
        f"{hw['_platform']['flash_bytes'] // 1024} KB Flash, "
        f"{hw['_platform']['sram_bytes']} B SRAM, no hardware multiplier, no FPU. "
        f"Built with {hw['_platform']['compiler']}.")
    add("")
    add("Every figure is labelled **M** measured on the device, **D** derived from two "
        "measurements, or **A** computed analytically from the model. The distinction "
        "matters: power is measured, latency is measured, and energy is neither — it is "
        "their product.")
    add("")

    # ---- layer 1 -----------------------------------------------------------
    add("## 1. Accuracy (software, HAPT, 5 seeds)")
    add("")
    add("| Cell | Equal capacity, H=16 | Equal byte budget | Route at the budget | Deployed config |")
    add("|---|---|---|---|---|")
    for c in CELLS:
        m1, s1 = tier1_hapt(c)
        m2, s2, route = budget_hapt(c)
        dep = hw["cells"][c]["deployed_f1"]
        add(f"| {c} | {fmt(m1)} ± {fmt(s1)} | {fmt(m2)} ± {fmt(s2)} | {route} | {fmt(dep, 4)} |")
    add("")
    add("The two regimes disagree, and that disagreement is the point: at equal hidden "
        "size the GRU is the better cell, while at a fixed byte budget each cell is "
        "compressed by whatever route suits it. The deployed column is a single "
        "configuration (seed 0), reported alongside the distributions rather than "
        "instead of them.")
    add("")

    # ---- layer 2 -----------------------------------------------------------
    add("## 2. Bench deployment — sensor detached")
    add("")
    add("| Cell | Latency /step, LUT | no LUT | Power | Energy /window, LUT | no LUT | Flash | SRAM | Weights |")
    add("|---|---|---|---|---|---|---|---|---|")
    add("| | **M** ms | **M** ms | **M** mW | **D** mJ | **D** mJ | **M** B | **M** B | **A** B |")
    for c in CELLS:
        h = hw["cells"][c]
        add(f"| {c} | {h['latency_ms']['lut']:.3f} | {h['latency_ms']['no_lut']:.3f} "
            f"| {h['power_mw']['lut']:.2f} "
            f"| {h['energy_mj_per_window']['lut']:.1f} | {h['energy_mj_per_window']['no_lut']:.1f} "
            f"| {h['flash_bytes']} | {h['sram_bytes']} | {h['weight_bytes']} |")
    add("")
    add("Power is flat across all three cells — within one INA226 least-significant bit — "
        "so it is a property of the platform, not of the model. Energy per window is not "
        "flat, because it is power multiplied by a latency that does differ. Reading the "
        "power column alone would suggest the activation implementation is free; it is not.")
    add("")
    add(f"*{hw['_caveat']}*")
    add("")

    # ---- layer 3 -----------------------------------------------------------
    add("## 3. Sensor in the loop — MPU6050 actually attached")
    add("")
    add(f"End-to-end per sample, mean over {sensor['n_samples_per_run']} consecutive "
        f"samples, against the {sensor['deadline_ms']:.0f} ms budget of "
        f"{sensor['sample_rate_hz']} Hz sampling.")
    add("")
    add("| Cell | LUT @100 kHz | LUT @10 kHz | no LUT @100 kHz | no LUT @10 kHz |")
    add("|---|---|---|---|---|")
    for c in CELLS:
        row = [f"| {c} "]
        for lut, khz in ((1, 100), (1, 10), (0, 100), (0, 10)):
            r = live[(c, lut, khz)]
            mark = "✅" if r["realtime"] else "❌"
            row.append(f"| {r['e2e_ms']:.2f} {mark} ")
        add("".join(row) + "|")
    add("")
    sp = sensor["system_power_mw"]
    add(f"System power (**M**): {sp['i2c_100khz']['typical']:.1f} mW at 100 kHz, "
        f"{sp['i2c_10khz']['min']:.1f}–{sp['i2c_10khz']['max']:.1f} mW at 10 kHz, "
        f"independent of cell and of the activation implementation — against "
        f"{sp['bench_mcu_only']['typical']:.1f} mW for the MCU alone. Attaching the "
        f"sensor roughly doubles system power.")
    add("")
    add("Only one column passes. Table-based activations alone are not sufficient, and "
        "a fast sensor bus alone is not sufficient; the deadline is met only when both "
        "hold. At 10 kHz the sensor read costs 8.4 ms before any inference begins, which "
        "is invisible to a benchmark that feeds the model from memory.")
    add("")

    # ---- what the layers say together -------------------------------------
    add("## Reading the three layers together")
    add("")
    add("| | Best cell | By what margin |")
    add("|---|---|---|")
    t = {c: tier1_hapt(c)[0] for c in CELLS}
    b = {c: budget_hapt(c)[0] for c in CELLS}
    lat = {c: hw["cells"][c]["latency_ms"]["lut"] for c in CELLS}
    en = {c: hw["cells"][c]["energy_mj_per_window"]["lut"] for c in CELLS}
    e2e = {c: live[(c, 1, 100)]["e2e_ms"] for c in CELLS}
    mem = {c: hw["cells"][c]["flash_bytes"] for c in CELLS}

    def best(d, lower_is_better=False, unit="", nd=3):
        order = sorted(d, key=d.get, reverse=not lower_is_better)
        win, second = order[0], order[1]
        gap = f"{abs(d[win] - d[second]):.{nd}f}" + (f" {unit}" if unit else "")
        return win, f"| {win} | {gap} over {second} |"

    axes = [
        ("Accuracy, equal capacity", best(t)),
        ("Accuracy, equal byte",     best(b)),
        ("Bench latency",            best(lat, True, "ms")),
        ("Energy per window",        best(en, True, "mJ", 1)),
        ("End-to-end with sensor",   best(e2e, True, "ms", 2)),
        ("Flash footprint",          best(mem, True, "B", 0)),
    ]
    for label, (_, row) in axes:
        add(f"| {label} " + row)
    add("")

    winners = {w for _, (w, _) in axes}
    if len(winners) == 1:
        sole = winners.pop()
        add(f"On HAPT the {sole} wins every axis — accuracy under both regimes, latency, "
            f"energy, end-to-end time with the sensor attached, and footprint. The "
            f"hardware layer does not overturn the software ranking here; it agrees with "
            f"it. Stating that plainly matters, because the ranking reversal this work "
            f"reports does not happen on this dataset.")
        add("")
        # the reversal lives on another dataset; say where, or this table misleads
        other = jload("best_route_summary.json")
        flips = [ds for ds, d in other.items()
                 if isinstance(d, dict) and d.get("winner") == "fastgrnn"
                 and ds not in RANK_EXCLUDED]
        if flips:
            add(f"Where it does happen is {', '.join(x.upper() for x in flips)}: at the "
                f"same byte budget the winner there is FastGRNN, not the {sole}. The "
                f"deployment measurements above are HAPT-only, because the firmware "
                f"carries one model — so this table shows what the hardware costs, not "
                f"which cell to prefer in general.")
            add("")
        for ds, why in RANK_EXCLUDED.items():
            add(f"{ds.upper()} is reported elsewhere but carries no ranking claim: {why}.")
            add("")
    else:
        add("No cell wins every axis, and the axes do not agree on an ordering — which "
            "is the case against reporting a single winner: preference depends on which "
            "constraint is binding, and on this device several bind at once.")
        add("")
    add("---")
    add("")
    add("Sources: `hardware_bench.json`, `sensor_in_loop_matrix.json`, "
        "`best_route_summary.json`, `baseline_*_h16_s*_e120.json`. "
        "Measurement conditions and the reproducibility audit: `REPRODUCIBILITY.md`.")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", action="store_true", dest="to_stdout")
    args = ap.parse_args()
    text = build()
    if args.to_stdout:
        print(text)
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT} ({len(text.splitlines())} lines)")
